language: python

python:
- 3.6

cache:
  - pip

install:
- pip install -r requirements.txt

script:
- make publish

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
  - OUTPUTDIR: output
  - GH_REF: github.com/theskumar/blog.git
  - secure: "HkrUDcSV3Bw/wPgOKMpjgcyLQc7OQAdDHFXp8daJZowa3rs0aUbfLEhTDX2nkWHKuueG7p7TaV7jccIHtjo9EzNn24bVyoPrRB80jWvVtaYdqDL8mLQzbTORHyY5z/8cW3wh1uuKE2+HAcdXyqP7qSviRE/8laj1nv3a4w5TSGk="

after_success:
  - make github_travis
