name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        run: make publish
        env:
          OUTPUTDIR: output

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output # The directory where Pelican outputs the built site
          publish_branch: gh-pages # Branch to deploy to
          force_orphan: true # Make sure the gh-pages branch only contains the latest build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
